//Spec file is necessary for the playwright scripts to be running. Do not edit this file unless its necessary
import { test, expect, type Page } from '@playwright/test';
import {TestConfig} from '../test.config';
import {LoginPage} from '../pages/Login.ts';
import {Home} from '../pages/HomePage.ts';

test.describe.serial('Start test',() => {
    let page: Page;
    let config: TestConfig;
    let login: LoginPage;
    let homePage: Home;

    test.beforeAll(async ({browser}) => {
    // console.log("This is before all tests");
        page = await browser.newPage();
        login = new LoginPage(page);
        const config = new TestConfig();  //import all the variables from test.config.ts file    
        await page.goto(config.appUrl);  
       // await page.pause();
         
    });

    test('Open the application URL and verify the login page is opened successfully', async () => {
    //Open browser and navigate to URL
        const login = new   LoginPage(page);  //Create an instance of the Login page
        await login.isPageExist();  //Check if the login page is opened successfully
        console.log("Login page is opened successfully");
        const config = new TestConfig();  //import all the variables from test.config.ts file
        await login.loginToApp(config.user, config.password);  //Perform login action with username and password from config
    });

    test('Verify the Home page', async () => {
        const homePage = new Home(page);  //Create an instance of the Home page
        await homePage.isPageExist();//Check if the home page is opened successfully after login    
        console.log("Home page is opened successfully");
    });

    test("Verify the hamburger option", async () => {
        const homepage = new Home(page);  //Create an instance of the Home page
        await homepage.clickHamburgerMenu(); //Click on the hamburger menu
        console.log("Hamburger menu clicked successfully");
    });

    test("Verify the logout button", async () => {
        const homepage = new Home(page);  //Create an instance of the Home page
        await homepage.clickLogoutButton();
        console.log("Logout button clicked successfully");
    });

    
    // Optional: Clean up after all tests are done
    test.afterAll(async () => {
       // await page.pause();
        await page.close();
    });
});
/*
test('Verify the Home page', async ({ page }) => {

    const config = new TestConfig();
    await page.goto(config.appUrl);  //Open browser and navigate to URL
    const login = new   LoginPage(page);  //Create an instance of the Login page
    await login.isPageExist();  //Check if the login page is opened successfully

    await login.loginToApp(config.user, config.password);  //Perform login action with username and password from config 
    
    const homePage = new Home(page);  //Create an instance of the Home page
    await homePage.isPageExist();  //Check if the home page is opened successfully after login
});
*/